baseurl = "/"
copyright = "Amazing-Gao ‚Äî All rights reserved."
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
title = "Amazing-Gao ÂÆûÂú®ÊòØÈ´ò"

paginate = 5
paginatePath = "page"

canonifyURLs = true
preserveTaxonomyNames = true

disqusShortname = "amazingao"

[permalinks]
posts = "/posts/:year/:month/:slug"
books = "/books/:slug"

[author]
email = "amazing.gao@qq.com"
name = "AmazingGao"

[taxonomies]
categories = "categories"
series = "series"
tags = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # change to false to disable inclusion of rawHTML and math functions
      xhtml = false
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    style = "monokai"
    tabWidth = 2

[params]
author = "Amazing Gao"
introDescription = "Find, discover, explorer and enjoy!"
numberOfTagsShown = 10
codeMaxLines = 200
codeLineNumbers = true
enableMathNotation = true
mainSections = ["posts"]
centerLogo = false
logo = "images/avatar.jpeg"
mobileNavigation = "left"
languageMenuName = "üåê"
comment = true
figurePositionShow = false
figurePositionLabel = "Figure"
numberOfRecentPosts = 5
numberOfFeaturedPosts = 5
dateFormat = "2006-01-02"
customJS = ["js/baidu.js", "//cdn.bootcss.com/mermaid/8.4.8/mermaid.min.js"]
